package exercises;

import java.util.ArrayList;

/*
<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
 */
public class Problem2 {
    public static void main(String[] args) {
        ArrayList<Integer> lista = fibonaciNumbersMaxNum(4000000);
        int suma = 0;
        for (Integer numero : lista) {
            if (is2Multiply(numero)) {
                suma += numero;
            }
        }
        System.out.println(suma);
    }

    public static ArrayList fibonaciNumbersMaxNum(int sum) {
        ArrayList lista = new ArrayList();
        int suma = 0;
        int aux1 = 0;
        int aux2 = 1;
        while (suma < sum) {
            suma = aux1 + aux2;
            lista.add(suma);
            aux1 = aux2;
            aux2 = suma;
        }
        lista.remove(lista.size() - 1);
        return lista;
    }

    public static boolean is2Multiply(int num) {
        return (num % 2) == 0;
    }
}